#!/bin/bash
#Set job requirementsclass_weight./
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --gpus=1
#SBATCH --partition=gpu
#SBATCH --time=48:00:00
 
#Loading modules
module load 2021
module load scikit-build/0.11.1-GCCcore-10.3.0
module load OpenCV/4.5.3-foss-2021a-CUDA-11.3.1-contrib
module load TensorFlow/2.6.0-foss-2021a-CUDA-11.3.1

#Copy input file to scratch
USER_DIR_NAME="LNA22_t"
DATA_DIR_NAME="Data"
mkdir -p "$TMPDIR"/"$USER_DIR_NAME"/in_dir
mkdir -p "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir
cp -R "$HOME"/"$DATA_DIR_NAME"/LUNA22_prequel/ "$TMPDIR"/"$USER_DIR_NAME"/in_dir
cp -R "$HOME"/"$DATA_DIR_NAME"/gen_data_dir/ "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir

#Create output directory on scratch
mkdir "$TMPDIR"/"$USER_DIR_NAME"/output_dir
mkdir "$HOME"/"$USER_DIR_NAME"/terminal_logs

# Activate venv
python -m venv ./venv
source ./venv/bin/activate

pip install scikit-image
pip install matplotlib
pip install tensorflow-addons
pip install click
pip install simpleitk
pip install sklearn

#Execute a Python program located in $HOME, that takes an input file and output directory as arguments.
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "resnet18" --run_name "resnet18_undersample" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_r18u_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "resnet18" --run_name "resnet18_undersample" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_r18u_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "resnet18" --run_name "resnet18_normal" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_r18n_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "resnet18" --run_name "resnet18_normal" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_r18n_log.txt

python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "resnet50" --run_name "resnet50_undersample" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_r50u_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "resnet50" --run_name "resnet50_undersample" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_r50u_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "resnet50" --run_name "resnet50_normal" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_r50n_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "resnet50" --run_name "resnet50_normal" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_r50n_log.txt

python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "vgg16" --run_name "vgg16_undersample" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_v16u_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "vgg16" --run_name "vgg16_undersample" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_v16u_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "vgg16" --run_name "vgg16_normal" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_v16n_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "vgg16" --run_name "vgg16_normal" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_v16n_log.txt

python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "vgg19" --run_name "vgg19undersample" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_v19u_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "vgg19" --run_name "vgg19_undersample" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_v19u_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "vgg19" --run_name "vgg19_normal" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_v19n_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "vgg19" --run_name "vgg19_normal" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_v19n_log.txt

python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "inceptionresnet" --run_name "inceptionresnet_undersample" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_iru_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "inceptionresnet" --run_name "inceptionresnet_undersample" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_iru_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "inceptionresnet" --run_name "inceptionresnet_normal" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_irn_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "inceptionresnet" --run_name "inceptionresnet_normal" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_irn_log.txt

python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "efficientnetv0" --run_name "efficientnetv0_undersample" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_ev0u_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "efficientnetv0" --run_name "efficientnetv0_undersample" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_ev0u_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "efficientnetv0" --run_name "efficientnetv0_normal" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_ev0n_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "efficientnetv0" --run_name "efficientnetv0_normal" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_ev0n_log.txt

python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "efficientnetv2" --run_name "efficientnetv2_undersample" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_ev2u_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "efficientnetv2" --run_name "efficientnetv2_undersample" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_ev2u_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "efficientnetv2" --run_name "efficientnetv2_normal" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_ev2n_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "efficientnetv2" --run_name "efficientnetv2_normal" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_ev2n_log.txt

python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "densenet" --run_name "densenet_undersample" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_du_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "densenet" --run_name "densenet_undersample" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_du_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "densenet" --run_name "densenet_normal" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_dn_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "densenet" --run_name "densenet_normal" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_dn_log.txt

python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "simplecnn" --run_name "simplecnn_undersample" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_snu_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "simplecnn" --run_name "simplecnn_undersample" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat undersampling --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_snu_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "simplecnn" --run_name "simplecnn_normal" --problem "noduletype" --val_fraciton 0.075 --batch_size 15 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/noduletype_snn_log.txt
python "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/train.py --raw_data_dir "$TMPDIR"/"$USER_DIR_NAME"/in_dir/LUNA22_prequel --out_dir "$TMPDIR"/"$USER_DIR_NAME"/output_dir --gen_data_dir "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir --epochs 250 --base_model "simplecnn" --run_name "simplecnn_normal" --problem "malignancy" --val_fraciton 0.075 --batch_size 16 --sample_strat normal --preprocessing_type normal > "$HOME"/"$USER_DIR_NAME"/terminal_logs/malignancy_snn_log.txt


#Copy output directory from scratch to home
cp -r "$TMPDIR"/"$USER_DIR_NAME"/output_dir "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/
cp -r "$TMPDIR"/"$USER_DIR_NAME"/gen_data_dir "$HOME"/"$USER_DIR_NAME"/Lung-Nodule-Analysis-2022/
